### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by timounger** [timounger/ElsterBooks#1]
## TODOs

- [ ] Rechnungen erstellen
- [ ] Ausgaben hochladen
- [ ] Nach Jahr getrennt
- [ ] Abrechung nach Zahlungseingang, Rechnungsdatum, Veranstaltungsdatum
- [ ] XLM Elster Export
- [ ] Excel Export
- [ ] Rechnungen Word/PDF erstellen
- [ ] Vorsteueranmeldung Erinnerung
- [ ] Bankkontoanbindung
